[package]
name = "bevy_osc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7", default-features = false, features = [] }
rosc = "0.7"
nom = "7.1.1"

[dev-dependencies]
bevy = { version = "0.7", default-features = true }