[package]
name = "bevy_rosc"
version = "0.2.0"
edition = "2021"
description = "Send and receive OSC messages in bevy"
repository = "https://github.com/DrLuke/bevy_rosc"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "osc", "rosc"]
categories = ["network-programming"]

[dependencies]
bevy = { version = "0.8", default-features = false, features = [] }
# This should be rosc = 0.9 but there currently are a few unmerged fixes
rosc = { git = "https://github.com/DrLuke/rosc", branch = "minor_fixes"}

[dev-dependencies]
bevy = { version = "0.8", default-features = true }