[package]
name = "bevy_osc"
version = "0.1.0"
edition = "2021"
description = "Send and receive OSC messages in bevy"
repository = "https://github.com/DrLuke/bevy_rosc"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "osc", "rosc"]
categories = ["network-programming"]

[dependencies]
bevy = { version = "0.7", default-features = false, features = [] }
rosc = "0.7"
nom = "7.1"

[dev-dependencies]
bevy = { version = "0.7", default-features = true }